import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

const Page = ({ data }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div
          style={{
            background: '#000',
            color: '#FFF',
            width: '100%',
            padding: '10rem 2rem',
            marginBottom: '10rem',
          }}
        >
          SSR at: {data.now}
        </div>
        <section style={{ background: '#CCC', padding: '8px' }}>
          To{' '}
          <Link href="/">
            <a style={{ color: 'blue', textDecoration: 'underline' }}>
              Static Home Page
            </a>
          </Link>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(
    `https://nextjs-time-api.vercel-support.app/api/time`
  );
  const data = await res.json();

  console.log({ data });

  // Pass data to the page via props
  return { props: { data } };
}

export default Page;
